# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: banking-cm
  namespace: default
data:
  CONFIG_SERVER_URL: "http://config-server-svc"
  ACCOUNTS_URL: "http://accounts-svc"
  CARDS_URL: "http://cards-svc"
  DB_HOST: "banking-db.cyuanxrjfhqn.ap-south-1.rds.amazonaws.com"


---

# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: banking-sc
  namespace: default
type: Opaque
data:
  DB_USER_NAME: YWRtaW4K
  DB_PASSWORD: YmFua2luZ3B3ZAo=
  


